export const captionPool = [
  "Chewing gum stuck to the bottom of a table",
  "A man playing an umbrella as if it was a guitar",
  "A spider from mars",
  "An awkward waiting room",
  "Excellent timing",
  "Your vegetable friend",
  "Brushing your tongue",
  "A very disappointing Christmas",
  "Forgetting how to eat",
  "Eating spiderwebs",
  "Darth Vader at his day job",
  "Making an onion cry",
  "An Aztec sacrifice",
  "A man hiding in a pram",
  "A centaur lollipop man",
  "An exploding cuckoo clock",
  "Eye-wateringly strong pickles",
  "A staring contest",
  "Licking people's shoes",
  "Abducted by butterflies",
  "What really happened to the dinosaurs",
  "Seeing a man about a horse",
  "Combing your hair with a hedgehog",
  "Frisbee decapitation",
  "Giraffe limbo contest",
  "Biting off more than you can chew",
  "Polishing a turd",
  "Cleaning your pipes",
  "Cereal killer",
  "Freezing your own head",
  "A T-Rex with a brand new handbag",
  "Mittens on a kitten",
  "More melons than you can carry",
  "Deflating an elephant",
  "Bottle-feeding a pig",
  "A supermodel with hobbit feet",
  "Angry potatoes meeting",
  "Bodybuilding toast",
  "Marrying a tiger",
  "The octopus who's late to the party",
  "A baby orchestra",
  "A train flying over a rainbow",
  "A lighthouse on fire",
  "Making your teddy bears fight to the death",
  "Broccoli ice cream",
  "Playing chess in a thunderstorm",
  "Accidentally stapling your hand to a cat",
  "Wind blowing someone over",
  "The Monkey King",
  "Choo, choo!",
  "Snapping a TV in half with your bare hands",
  "A leopard struggling to do its taxes",
  "Getting lost in a furniture shop",
  "Explaining knock-knock jokes to a parrot",
  "Sad Robocop",
  "Brian Blessed riding into battle",
  "A squirrel knitting",
  "A seal posting a letter",
  "A cucumber brushing its hair",
  "Happy Potter being breatalyzed by the police",
  "A woman trying to buy a tortoise",
  "A software engineer learning Javascript",
  "A banana playing monopoly",
  "Running away from your fears",
  "A car boot sale full of frogs",
  "Wearing your hair in a towel",
  "Running with scissors",
  "Camping in space",
  "A ghost playing Operation",
  "Iron Man doing the ironing",
  "afternoon tea with the queen",
  "Finding wally in wheres wally",
  "Making mashed potato",
  "A snake trying to climb a tree",
  "Eating your own foot",
  "I hate the green flashing light",
  "Hello. I have the urge to kill",
  "Rubber ducks are planning world domination!",
  "I know kung fu",
  "Fat kids are harder to kidnap",
  "Don’t mess with me! I have a stick!",
  "Ha ha! I don’t get it",
  "I am pretending to be a tomato",
  "Never set yourself on fire",
  "The banana has legs!",
  "Banana suicide!",
  "Back off! The ice cream is mine!",
  "I am here to install your cushion",
  "Your hands are really hairy",
  "Tomatoes are depressing",
  "My eyebrow died",
  "A jigsaw puzzle of a jigsaw puzzle",
  "Sharks with guns",
  "Hugging your favourite hammer",
  "A tree growing out of a gorilla's back",
  "King Kong doing his laundry",
  "Eating too many easter eggs",
  "A painting that is out of place",
  "Squirrels at war",
  "A silent rave",
  "A game that makes no sense",
  "Going backwards in time",
  "A successful businessman",
  "Ants take over the world",
  "An angry rhombus",
  "Three geese with tophats",
  "Lemmings",
  "A doughnut biker gang",
  "Jumping for joy",
  "Recycling a joke",
  "A stylish viking",
  "Trees discussing a dinner menu",
  "Overflowing with porridge",
  "A surprise pancake",
  "A malfunctioning toilet",
  "Cold toast",
  "Selling rice",
  "No country for old men",
  "Emus with walking sticks",
  "Llamas with hats",
  "A snowman with a chainsaw",
  "A deadly conga line",
  "Three more pies",
  "A mysterious trapdoor",
  "A stitch in time saves nine",
  "Neon sunglasses",
  "The best shoes",
  "Winning a frisbee contest",
  "Running from the president",
  "Dinosaur police",
  "Too big for the boat",
  "Rancid butter",
  "Colourful jeans",
  "Teaching a shark to tapdance",
  "An old chimp",
  "Blinded by science",
  "A panda dentist",
  "The lamp is cold",
  "A fridge in a trenchcoat",
  "Buying rollerskates",
  "Dying your hair",
  "Climbing the corporate ladder",
  "A shy panther",
  "Procrastination",
  "Animal instincts",
  "Stealing a seaplane",
  "Shopping for dice",
  "Bringing a spoon to a knife fight",
  "Dancing underwater",
  "Running in the moonlight",
  "A parade of orks",
  "Tea time is over",
  "Back to the future",
  "An elaborate question mark",
  "Emailing a camel",
  "Driving without wheels",
  "Comfy pajamas",
  "A cherry blossom golem",
  "Sacrificing a fruit",
  "A business leopard",
  "A punch card that punches back",
  "The last dodo",
  "Reading the writing on the ceiling",
  "Examining the alphabet",
  "A sunburnt giraffe",
  "A badger millionaire",
  "A dog looking for a shoe",
  "Penguins on holiday",
  "A cabbage knight",
  "Ducks playing poker",
  "An easter egg fighting a real egg",
  "Deadly boardgames",
  "A time machine for ants",
  "Not enough chocolate",
  "Blue eggs and ham",
  "A pokemon in disguise",
  "A dragon befriending a hamster",
  "Emu business meeting",
  "The cake is a lie",
  "Landlord fox",
  "My goat is on fire",
  "Radioactive bees",
  "A wounded crocodile",
  "Bear on a bike",
  "Mining for diamonds",
  "An infinite apple tree",
  "An easy sudoku",
  "A kindhearted pirate",
  "Remote controlled tortoise",
  "Anti-gravity boots",
  "A circuitboard",
  "Time for a new calendar",
  "The stone age",
  "A dangerous waterslide",
  "Marrying a bat",
  "A dragon scientist",
  "A cozy cottage",
  "A petrol-powered penguin",
  "Gnome assembly line",
  "Cardboard armour",
  "Books in my beard",
  "Videogame violence",
  "Jousting with lamp-posts",
  "Monkeys on typewriters",
  "Winning at catan",
  "Among us imposter",
  "Pikachu peeked at you",
  "Cake made from raddishes",
  "Pj party disco time",
  "Tea party for teddies",
  "Sunflower seed oil",
  "Hen do for a hen",
  "Ceilidh music is too loud",
  "Twilight fan parade",
  "Noisy library",
  "Octopus bar man",
  "Fox washing dishes",
  "Gardening scarecrow",
  "Walrus at the beach",
  "Rain puddle adventure",
  "Cinema trip accident",
];
